// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9eKE7vHrhcSwkA6I7ZpUff5fA7Iv5xdE',
    appId: '1:451476755427:web:1f975d8cd5297525b406d6',
    messagingSenderId: '451476755427',
    projectId: 'edutrack-92a9a',
    authDomain: 'edutrack-92a9a.firebaseapp.com',
    storageBucket: 'edutrack-92a9a.firebasestorage.app',
    measurementId: 'G-CP05JSN0QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZUId0ESpbuIF-RKPSTAce-kbajujvEIs',
    appId: '1:451476755427:android:fa02ab86a263c30db406d6',
    messagingSenderId: '451476755427',
    projectId: 'edutrack-92a9a',
    storageBucket: 'edutrack-92a9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdRLkcLPWb7S_UzN2izcniAoyTFQzXhzg',
    appId: '1:451476755427:ios:842c5073fa9e5a04b406d6',
    messagingSenderId: '451476755427',
    projectId: 'edutrack-92a9a',
    storageBucket: 'edutrack-92a9a.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdRLkcLPWb7S_UzN2izcniAoyTFQzXhzg',
    appId: '1:451476755427:ios:842c5073fa9e5a04b406d6',
    messagingSenderId: '451476755427',
    projectId: 'edutrack-92a9a',
    storageBucket: 'edutrack-92a9a.firebasestorage.app',
    iosBundleId: 'com.example.eduTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9eKE7vHrhcSwkA6I7ZpUff5fA7Iv5xdE',
    appId: '1:451476755427:web:22d3b4a6f0189f25b406d6',
    messagingSenderId: '451476755427',
    projectId: 'edutrack-92a9a',
    authDomain: 'edutrack-92a9a.firebaseapp.com',
    storageBucket: 'edutrack-92a9a.firebasestorage.app',
    measurementId: 'G-X0EH63MWL5',
  );
}
